data = [
    {"name": "Instagram", "follower_count": 600, "description": "Social media platform", "country": "United States"},
    {"name": "Cristiano Ronaldo", "follower_count": 580, "description": "Footballer", "country": "Portugal"},
    {"name": "Lionel Messi", "follower_count": 450, "description": "Footballer", "country": "Argentina"},
    {"name": "Ariana Grande", "follower_count": 350, "description": "Musician and actress", "country": "United States"},
    {"name": "Selena Gomez", "follower_count": 420, "description": "Musician and actress", "country": "United States"},
    {"name": "Kylie Jenner", "follower_count": 400, "description": "Reality TV star and businesswoman", "country": "United States"},
    {"name": "Kim Kardashian", "follower_count": 370, "description": "Reality TV star and businesswoman", "country": "United States"},
    {"name": "Dwayne Johnson", "follower_count": 380, "description": "Actor and professional wrestler", "country": "United States"},
    {"name": "Taylor Swift", "follower_count": 320, "description": "Musician", "country": "United States"},
    {"name": "Virat Kohli", "follower_count": 250, "description": "Cricketer", "country": "India"},
    {"name": "Neymar Jr", "follower_count": 220, "description": "Footballer", "country": "Brazil"},
    {"name": "Kendall Jenner", "follower_count": 280, "description": "Model", "country": "United States"},
    {"name": "Justin Bieber", "follower_count": 290, "description": "Musician", "country": "Canada"},
    {"name": "National Geographic", "follower_count": 150, "description": "Magazine", "country": "United States"},
    {"name": "Nike", "follower_count": 200, "description": "Sports brand", "country": "United States"},
    {"name": "Khaby Lame", "follower_count": 160, "description": "TikTok creator", "country": "Italy"},
    {"name": "Zendaya", "follower_count": 170, "description": "Actress and musician", "country": "United States"},
    {"name": "Shakira", "follower_count": 140, "description": "Musician", "country": "Colombia"},
    {"name": "Kourtney Kardashian", "follower_count": 160, "description": "Reality TV star", "country": "United States"},
    {"name": "Miley Cyrus", "follower_count": 150, "description": "Musician and actress", "country": "United States"},
    {"name": "LeBron James", "follower_count": 160, "description": "Basketball player", "country": "United States"},
    {"name": "Billie Eilish", "follower_count": 110, "description": "Musician", "country": "United States"},
    {"name": "Rihanna", "follower_count": 130, "description": "Musician and businesswoman", "country": "Barbados"},
    {"name": "Emma Watson", "follower_count": 120, "description": "Actress", "country": "United Kingdom"},
    {"name": "Chris Hemsworth", "follower_count": 100, "description": "Actor", "country": "Australia"},
    {"name": "Shah Rukh Khan", "follower_count": 95, "description": "Actor", "country": "India"},
    {"name": "Gal Gadot", "follower_count": 90, "description": "Actress", "country": "Israel"},
    {"name": "Cardi B", "follower_count": 80, "description": "Musician", "country": "United States"},
    {"name": "Drake", "follower_count": 85, "description": "Musician", "country": "Canada"},
    {"name": "David Beckham", "follower_count": 75, "description": "Former footballer", "country": "United Kingdom"},
]
